- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: essentials

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: mysql

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: php

- hosts: all
  become: true
  become_user: ubuntu
  gather_facts: false
  tasks:
    - include_role:
        name: composer

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: apache
